version: '3'

services:
  web:
    build:
      dockerfile: Dockerfile
      context: .
    image: ippolab/athena-backend:dev
    container_name: athena_back
    depends_on:
      - db
    env_file:
      - .env
    ports:
      - "8000:8000"
  db:
    image: postgres:11.2-alpine
    container_name: athena_pgdb
    env_file:
      - .env